/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VyhladajKontakt.java
 *
 * Created on Dec 1, 2011, 1:21:30 AM
 */
package istel.swingui.formular;

import istel.Jadro;
import istel.Main;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.table.AbstractTableModel;
import org.jdesktop.application.Action;

/**
 *
 * @author pipo
 */
public class VyhladajKontakt extends javax.swing.JPanel {

    /** Creates new form VyhladajKontakt */
    public VyhladajKontakt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPriezvisko = new javax.swing.JTextField();
        jTextFieldMeno = new javax.swing.JTextField();
        jTextFieldObec = new javax.swing.JTextField();
        jTextFieldPSC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(580, 500));
        setPreferredSize(new java.awt.Dimension(680, 500));
        setRequestFocusEnabled(false);

        jLabel2.setText("Priezvisko:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText("Meno:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel5.setText("PSC:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setText("Obec:");
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldPriezvisko.setName("jTextFieldPriezvisko"); // NOI18N

        jTextFieldMeno.setName("jTextFieldMeno"); // NOI18N

        jTextFieldObec.setName("jTextFieldObec"); // NOI18N

        jTextFieldPSC.setName("jTextFieldPSC"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(VyhladajKontakt.class, this);
        jButton1.setAction(actionMap.get("Vyhladat")); // NOI18N
        jButton1.setText("Vyhladat");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMeno, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPriezvisko, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldObec, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPSC, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldObec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String meno = jTextFieldMeno.getText();
        String priezvisko = jTextFieldPriezvisko.getText();
        String obec = jTextFieldObec.getText();
        String psc = jTextFieldPSC.getText();
        
        
        ResultSet result = Main.jadro.vyhladajKontakt(meno, priezvisko, obec, psc);
        Tabulka tabulka = new Tabulka(result);
        jTable1.setModel(tabulka);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMeno;
    private javax.swing.JTextField jTextFieldObec;
    private javax.swing.JTextField jTextFieldPSC;
    private javax.swing.JTextField jTextFieldPriezvisko;
    // End of variables declaration//GEN-END:variables

private class Tabulka extends AbstractTableModel {
 
        private Object[][] data;
        protected String[] columnNames = {"Priezvisko", "Meno", "Tel.cislo" , "Ulica" ,"Cislo domu", "Obec" , "PSC"};
        private List list;
        public Tabulka(ResultSet result) {
            try {
//                list = new ArrayList();
//                while (result.next()) list.add(result.getString(TOOL_TIP_TEXT_KEY));
//              
                int count  = 0;
                //while(result.next()) count++;
                result.last();
                count = result.getRow();                     
                
                this.data = new Object[count][8];
                result.first();
                //System.out.println(result.getString(1));
                //System.out.println();
                //result.previous();
                //while (result.next())
                for(int i = 1; i <= count; i++ )
                {
                    System.out.println(result.getString(1));
                    this.data[result.getRow() -1 ][0] = result.getString(1);
                    System.out.println(result.getString(2));
                    this.data[result.getRow() -1 ][1] = result.getString(2);
                    System.out.println(result.getString(3));
                    this.data[result.getRow() -1 ][2] = result.getString(3);
                    System.out.println(result.getString(4));
                    this.data[result.getRow() -1 ][3] = result.getString(4);
                    System.out.println(result.getString(5));
                    this.data[result.getRow() -1 ][4] = result.getString(5);
                    System.out.println(result.getString(6));
                    this.data[result.getRow() -1 ][5] = result.getString(6);
                    System.out.println(result.getString(7));
                    this.data[result.getRow() -1 ][6] = result.getString(7);
                    
                    result.next();
                }
                
                System.out.println(getRowCount());
            } catch (SQLException ex) {
                Logger.getLogger(VyhladajKontakt.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
 
        @Override
        public int getRowCount() {
            return data.length;
        }
 
        @Override
        public int getColumnCount() {
            return columnNames.length;
        }
 
        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }
 
        @Override
        public Object getValueAt(int row, int column) {
            return data[row][column];
        }
    }

  

}
