/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VyhladajKontakt.java
 *
 * Created on Dec 1, 2011, 1:21:30 AM
 */
package istel.swingui.formular;

import istel.Main;
import istel.kontakt.Adresa;
import istel.kontakt.Cislo;
import istel.kontakt.Kontakt;
import istel.kontakt.Osoba;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author pipo
 */
public class VyhladajKontakt extends javax.swing.JPanel {

    private String titulok = "Hľadaj kontakt";
    /** Creates new form VyhladajKontakt */
    public VyhladajKontakt() {
        initComponents();
        jLabelChyba.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPriezvisko = new javax.swing.JTextField();
        jTextFieldMeno = new javax.swing.JTextField();
        jTextFieldObec = new javax.swing.JTextField();
        jTextFieldPSC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVyhladat = new javax.swing.JButton();
        jLabelChyba = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(580, 500));
        setPreferredSize(new java.awt.Dimension(680, 500));
        setRequestFocusEnabled(false);

        jLabel2.setText("Priezvisko:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText("Meno:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel5.setText("PSC:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setText("Obec:");
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldPriezvisko.setName("jTextFieldPriezvisko"); // NOI18N

        jTextFieldMeno.setName("jTextFieldMeno"); // NOI18N

        jTextFieldObec.setName("jTextFieldObec"); // NOI18N

        jTextFieldPSC.setName("jTextFieldPSC"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButtonVyhladat.setText("Vyhľadať");
        jButtonVyhladat.setName("jButtonVyhladat"); // NOI18N
        jButtonVyhladat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVyhladatActionPerformed(evt);
            }
        });

        jLabelChyba.setForeground(new java.awt.Color(255, 0, 0));
        jLabelChyba.setText("Aspoň jeden údaj je povinný");
        jLabelChyba.setName("jLabelChyba"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(18, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldPSC)
                            .addComponent(jTextFieldPriezvisko)
                            .addComponent(jTextFieldMeno, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                            .addComponent(jTextFieldObec)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonVyhladat)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelChyba)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldObec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVyhladat)
                    .addComponent(jLabelChyba))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVyhladatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVyhladatActionPerformed
        String meno = jTextFieldMeno.getText().trim();
        String priezvisko = jTextFieldPriezvisko.getText().trim();
        String obec = jTextFieldObec.getText().trim();
        String psc = jTextFieldPSC.getText().trim();


        if (meno.equalsIgnoreCase("")
                && priezvisko.equalsIgnoreCase("")
                && obec.equalsIgnoreCase("")
                && psc.equalsIgnoreCase("")) {
            jLabelChyba.setVisible(true);
        } else {
            jLabelChyba.setVisible(false);
            //deepe uprava
            Adresa adresa = new Adresa(obec, psc, null, null);
            Cislo cislo = new Cislo(null);
            Osoba osoba = new Osoba(meno, priezvisko);
            Kontakt kontakt = new Kontakt(osoba, adresa, cislo);

            Tabulka tabulka = new Tabulka(Main.jadro.vyhladajKontakt(kontakt));
            jTable1.setModel(tabulka);
        }
    }//GEN-LAST:event_jButtonVyhladatActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVyhladat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelChyba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMeno;
    private javax.swing.JTextField jTextFieldObec;
    private javax.swing.JTextField jTextFieldPSC;
    private javax.swing.JTextField jTextFieldPriezvisko;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the titulok
     */
    public String getTitulok() {
        return titulok;
    }

    private class Tabulka extends AbstractTableModel {

        private Object[][] data;
        protected String[] columnNames = {"Priezvisko", "Meno", "Telefonné čislo", "Ulica", "Číslo domu", "Obec", "PSC"};
        private ArrayList<Kontakt> kontaky;

        public Tabulka(ArrayList<Kontakt> kontaky) {
            this.kontaky = kontaky;
            this.data = new Object[kontaky.size()][7];
            for (int index = 0; index < kontaky.size(); index++) {
                this.data[index][0] = kontaky.get(index).getOsoba().getPriezvisko();
                this.data[index][1] = kontaky.get(index).getOsoba().getMeno();
                this.data[index][2] = kontaky.get(index).getCisla().get(0).getCislo();
                this.data[index][3] = kontaky.get(index).getAdresa().getUlica();
                this.data[index][4] = kontaky.get(index).getAdresa().getCisloDomu();
                this.data[index][5] = kontaky.get(index).getAdresa().getObec();
                this.data[index][6] = kontaky.get(index).getAdresa().getPsc();
            }

        }

        @Override
        public int getRowCount() {
            return data.length;
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        @Override
        public Object getValueAt(int row, int column) {
            return data[row][column];
        }
    }
}
