/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VymazKontakt2.java
 *
 * Created on Dec 9, 2011, 10:21:12 PM
 */
package istel.swingui.formular;

import istel.Main;
import istel.kontakt.Adresa;
import istel.kontakt.Cislo;
import istel.kontakt.Kontakt;
import istel.kontakt.Osoba;

/**
 *
 * @author erik
 */
public class VymazKontakt extends javax.swing.JPanel {

    /** Creates new form VymazKontakt2 */
    public VymazKontakt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextMeno = new javax.swing.JTextField();
        jTextPriezvisko = new javax.swing.JTextField();
        jTextTelefon = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jVymazKontaktButton = new javax.swing.JButton();

        jLabel1.setText("Meno:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Priezvisko:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Cislo:");
        jLabel3.setName("jLabel3"); // NOI18N

        jTextMeno.setName("jTextMeno"); // NOI18N
        jTextMeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMenoActionPerformed(evt);
            }
        });

        jTextPriezvisko.setName("jTextPriezvisko"); // NOI18N

        jTextTelefon.setName("jTextTelefon"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jVymazKontaktButton.setText("Vymaz kontakt");
        jVymazKontaktButton.setName("jVymazKontaktButton"); // NOI18N
        jVymazKontaktButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVymazKontaktButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                    .addComponent(jTextMeno, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                    .addComponent(jTextPriezvisko, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jVymazKontaktButton)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVymazKontaktButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jTextMenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMenoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextMenoActionPerformed

private void jVymazKontaktButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVymazKontaktButtonActionPerformed
 
    if(!jTextMeno.getText().equalsIgnoreCase("") && !jTextPriezvisko.getText().equalsIgnoreCase("") && !jTextTelefon.getText().equalsIgnoreCase("")){
        Adresa adresa= new Adresa(null, null, null, null);
        Cislo cislo = new Cislo(jTextTelefon.getText().trim());
        Osoba osoba = new Osoba(jTextMeno.getText().trim(), jTextPriezvisko.getText().trim());
        Kontakt kontakt = new Kontakt(osoba, adresa, cislo);
        
        if(Main.getJadro().zmazKontakt(kontakt)){
            //TODO: pridaj label na vypisanie ze vsetko prebehlo OK
        }else{
            //TODO: label nastav na chybu
        }
        
        System.out.println("DELETE * from cislo WHERE tel_cislo LIKE "+jTextTelefon.getText());
    }else {
           System.out.println("vypln vsetko");
    }// TODO add your handling code here:
}//GEN-LAST:event_jVymazKontaktButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextMeno;
    private javax.swing.JTextField jTextPriezvisko;
    private javax.swing.JTextField jTextTelefon;
    private javax.swing.JButton jVymazKontaktButton;
    // End of variables declaration//GEN-END:variables
}
